### ISSUE TITLE
Split out the board builder as npm module

### ISSUE THREAD

**Issue by kasbah** [mcous/svgerber#27]
I already started this because I wanted to use the board renderings on my own site (generated server-side).

https://github.com/kasbah/svgerber-board-builder

It does what I need already but still needs some clean-up and I will also bring the style in line with svgerber but I wanted to tentatively ask if you would be up for splitting it out as a module and adding it as a dependency here?

**Comment by mcous** [comment]
I was just having the same thought! (Great minds and such...) Svgerber is a nice tech demo and all, but I've got a new project to do the same thing better, so I'm not really planning on adding features here.

I completely rewrote the board builder (with easier to understand code and complete test coverage) for a new webapp, but it's been languishing on my hard drive, despite the fact that I kind of wrote it like a module. I'll get it split out and posted in a few days (about to get on a 15 hour flight to Hong Kong, so it'll be a good time to work on it hah).

Keep an eye on the [trace space org](https://github.com/tracespace) over the next few days. Since I wrote it a little while ago, it doesn't incorporate some of your recent PRs here, so I could use your input and help!

**Comment by mcous** [comment]
Alright so I've posted the new-and-improved PCB stackup builder [here](https://github.com/tracespace/pcb-stackup). If you wanted to open a PR to move SVGerber over to it, I'd accept and appreciate it, but seeing as I'm trying to deprecate this site, I certainly don't expect you to. I'll leave this issue open until you decide either way.

The new one does not incorporate fixes for #18 (auto-unit conversion), #20 (fixing small gaps and auto-merging similar tool sizes), #23 (option to merge all tools into one), or #26 (Inkscape compatibility). So yeah, depending on what your needs are and if you want to use the new one, I could use help!

**Comment by mcous** [comment]
Closing because the board builder was split out and svgerber has been succeeded by http://viewer.tracespace.io
