### ISSUE TITLE
0 width dimension layer not handled properly

### ISSUE THREAD

**Issue by clemtaylor** [mcous/svgerber#28]
In eagle I normally use 0 width lines to make up the board dimension layer. svgerber does not seem to use the 0 width lines to define the board perimeter so the board dimension seems to be purely bounding box based.

This is a section from eagle:
![image](https://cloud.githubusercontent.com/assets/1316864/9639974/e90ec5ce-517c-11e5-987d-adc2697803b1.png)

And in gerbv:
![image](https://cloud.githubusercontent.com/assets/1316864/9639983/f4ce9f1a-517c-11e5-97f4-fd76c7a6083b.png)

In svgerber it renders as:
![image](https://cloud.githubusercontent.com/assets/1316864/9640001/0b2f1e2e-517d-11e5-8d98-7ecafdcd4acb.png)

If I set the width to non-zero, the board outline acts as a clipping plane:
![image](https://cloud.githubusercontent.com/assets/1316864/9640737/e551f8b2-5180-11e5-9eea-2e69ccee48b4.png)

0 width file: example.boardoutline.ger:
https://drive.google.com/open?id=0B8Rr7m3RxlciVlVST0ZhQzB0ZlU

non-zero width file example.non-zero.ger:
https://drive.google.com/open?id=0B8Rr7m3RxlciYzRHYVRteV9pRW8

**Comment by mcous** [comment]
I think the requirement for a line with a width came from some fabs recommending a 5 or 10 mil line width for the outline layer (e.g. [Advanced Circuits](http://www.4pcb.com/avoid-cam-hold/)). That being said, it's an arbitrary distinction that I'm fine with removing. The line width check is [here](https://github.com/mcous/svgerber/blob/master/src/build-board.coffee#L99).

If I find some time I'll patch this up. Otherwise I'd accept a PR!

**Comment by mcous** [comment]
Sorry for leaving this issue dangling! svgerber has been replaced by http://viewer.tracespace.io, and it does not care what width your outline paths are drawn with
