### ISSUE TITLE
Rendering issue in attached gerber

### ISSUE THREAD

**Issue by gadgetjunkie** [mcous/svgerber#29]
The gerber in pcb.bor.txt renders correctly in gcpreview and gerbv.

It has issues when displaying the svn generated by gerber-to-svg.

The attached png file is a screenshot of the file being displayed in gerbv.  

It looks like gerber-to-svg is having trouble with the tight arcs.

[pcb.bor.txt](https://github.com/mcous/svgerber/files/37480/pcb.bor.txt)
![screen shot 2015-11-17 at 10 21 45 pm](https://cloud.githubusercontent.com/assets/12651162/11231748/a5a4395c-8d79-11e5-9f46-9f35c352e798.png)

**Comment by mcous** [comment]
Hey, thanks for the issue. The arcs that don't draw properly are a result of the fact that the distance between the center of the arc and the start of the arc is different than the distance between the center and the end. Basically, it's a poorly generated Gerber file.

That being said, the radius check is really only for finding the correct arc center when arcs are drawn in single quadrant mode. These arcs are drawn in multi-quadrant mode, and I don't see any real danger in disabling the radius check for multi-quadrant mode. With the check disabled, it renders. Technically the rendered arcs are slightly off center, but it's better than nothing, I suppose.

Can you do me a favor and open this issue in [gerber-to-svg](https://github.com/mcous/gerber-to-svg)? I'll keep this issue here open until it is fixed there.

**Comment by gadgetjunkie** [comment]
Oops -- meant to open this in gerber-to-svn.  Closing this on.

**Comment by gadgetjunkie** [comment]
Hi Mike,

Thanks for the quick reply!  At the time, I thought I was submitting the issue to gerber-to-svn, but I now see the error in my ways.

I have opened the issue in gerber-to-svn like I should have originally (https://github.com/mcous/gerber-to-svg/issues/23) . I have also closed issue #29 in svgerber.

Thanks again for the quick reply, and for a very useful library!

Mike Williams
MacroFab, Inc.
